name: climafwps
channels:
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pip
- six
- pywps>=4.2.0
- owslib>=0.18
- jinja2
- click
- psutil
- climaf=1.1.1
- ncl
# cdo
- cdo
#- hdf5=1.10.3
#- libnetcdf=4.6.1
